name: Action Generate RSS Feed Full

on:
  push:
    branches: [ master ]
  #schedule:
  # - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  generate_feed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Refresh Token
      run: |
        curl -sSL https://git.io/install-xq | sudo bash
        curl -sSL -X "POST" -H "Authorization: Basic ${{ secrets.SPOTIFY_API }}" -d grant_type=client_credentials https://accounts.spotify.com/api/token | jq '.access_token' | tr -d '"' > token
        echo "BEARER=$(cat token)" >> $GITHUB_ENV
    - name: Composer Install
      run: composer install --prefer-dist --no-progress
    - name: xq install
      run: curl -sSL https://bit.ly/install-xq | sudo bash
    - name: Feed Generation
      run: php feed.php
    - name: RSS Tidy
      run: |
        pwd
        ls -lah
        mkdir -p feed
        ls -lah feed
        #cp feed/4rOoJ6Egrf8K2IrywzwOMk_temp.rss feed/4rOoJ6Egrf8K2IrywzwOMk.rss
        cat feed/4rOoJ6Egrf8K2IrywzwOMk_temp.rss >feed/4rOoJ6Egrf8K2IrywzwOMk.rss
        cat feed/4rOoJ6Egrf8K2IrywzwOMk.rss > feed/4rOoJ6Egrf8K2IrywzwOMk_readable.rss
        rm feed/4rOoJ6Egrf8K2IrywzwOMk_temp.rss
    - name: CleanUp
      run: rm -rf token
    - name: Commit
      continue-on-error: true
      run: |
        git pull origin main
        git push origin main
        git config --global user.name 'MikeeI'
        git config --global user.email 'MikeeI@users.noreply.github.com'
        git add -A
        if git status | grep -q modified; then
          echo "MODIFIED=1" >> "$GITHUB_ENV"
        fi
        git commit -am "Feed Generation"        
        git push
    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash
    - name: Ping Overcast
      run: curl --data-urlencode "urlprefix=https://spodcast.cdnly.eu/feed/4rOoJ6Egrf8K2IrywzwOMk.rss" https://overcast.fm/ping
