name: PHP Execution

on:
  push:
    branches: [ master ]
  schedule:
   - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  generate_feed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Refresh Token
      run: |
        curl -sSL https://git.io/install-xq | sudo bash
        curl -s -X "POST" -H "Authorization: Basic ${{ secrets.SPOTIFY_API }}" -d grant_type=client_credentials https://accounts.spotify.com/api/token | jq '.access_token' | tr -d '"' > token
        echo "BEARER=$(cat token)" >> $GITHUB_ENV
    - name: Composer Install
      run: composer install --prefer-dist --no-progress
    - name: Feed Generation
      run: php feed.php
    - name: RSS Tidy
      run: cat feed2.rss | xq > feed.rss
    - name: CleanUp
      run: rm -rf token
    - name: Commit
      continue-on-error: true
      run: |
        git pull origin main
        git push origin main
        git config --global user.name 'MikeeI'
        git config --global user.email 'MikeeI@users.noreply.github.com'
        git add -A
        git commit -am "Feed Generation"        
        git push
    - name: Ping Overcast
      run: curl --data-urlencode "urlprefix=https://github.com/MikeeI/php-feed-writer/blob/master/feed.rss" https://overcast.fm/ping
